services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
language: node_js
node_js:
  - "4.4.7"
env:
  - APP_ENV=test
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - "npm install -g mocha"
install:
  - npm install
script:
  - npm test
