language: node_js
node_js:
- 4.4.7
services:
- mongodb
env:
- APP_ENV=test
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - mongodb-3.0-precise
    packages:
    - g++-4.8
    - mongodb-org-server
before_script:
- sleep 15
before_install:
- npm install -g mocha
install:
- npm install
script:
- npm test
before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
